cache:
 directories:
 - "$HOME/.m2"
 - "$HOME/.sonar/cache"

addons:
  sonarcloud:
    organization: "adridash"
    token:
      secure: "1f225287b7d1e928d9d9254122b2353f81298972" # encrypted value of your token

services:
 - docker

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=adridash_sample-application-students
 - docker build -t adri/db-changelog ./sample-application-db-changelog-job
 - docker build -t adri/http-api ./sample-application-http-api-server
 - docker tag adri/db-changelog $DOCKER_USERNAME/dbchangelog:db1.0
 - docker tag adri/http-api $DOCKER_USERNAME/http:1.0
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push $DOCKER_USERNAME/dbchangelog
 - docker push $DOCKER_USERNAME/http

notifications:
 email:
   on_failure: never

   travis encrypt 

