cache:
 directories:
 - "$HOME/.m2"
 - "$HOME/.sonar/cache"

services:
 - docker

script:
 - mvn clean verify
 - docker build -t adri/db-changelog /home/travis/build/adridash/sample-application-students/sample-application-db-changelog-job
 - ls /home/travis/build/adridash/sample-application-students/sample-application-db-changelog-job/target/
 - docker build -t adri/http-api /home/travis/build/adridash/sample-application-students/sample-application-http-api-server

notifications:
 email:
   on_failure: never
   