cache:
 directories:
 - "$HOME/.m2"
 - "$HOME/.sonar/cache"

services:
 - docker

script:
 - mvn clean verify
 - docker build -t adri/db-changelog ./sample-application-db-changelog-job
 - docker build -t adri/http-api ./sample-application-http-api-server
 - docker tag adri/db-changelog $DOCKER_USERNAME/dbchangelog:db1.0
 - docker tag adri/http-api $DOCKER_USERNAME/http:1.0
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push $DOCKER_USERNAME/dbchangelog
 - docker push $DOCKER_USERNAME/http

notifications:
 email:
   on_failure: never
