cache:
 directories:
 - "$HOME/.m2"
 - "$HOME/.sonar/cache"

services:
 - docker

script:
 - mvn clean verify
 - docker build -t adri/db-changelog:db1.0 ./sample-application-db-changelog-job
 - docker build -t adri/http-api:http1.0 ./sample-application-http-api-server
 - docker tag adri/db-changelog adridash/repotest:db1.0
 - docker tag adri/http-api adridash/repotest:http1.0
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push adridash/repotest:db1.0
 - docker push adridash/repotest:http1.0

notifications:
 email:
   on_failure: never
