cache:
 directories:
 - "$HOME/.m2"
 - "$HOME/.sonar/cache"

services:
 - docker

script:
 - mvn clean verify
 - docker build -t adri/db-changelog ./sample-application-db-changelog-job
 - docker build -t adri/http-api ./sample-application-http-api-server

notifications:
 email:
   on_failure: never
